name: quality assurance

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  reporting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.19, 1.20 ]

    steps:
      - uses: actions/checkout@v3

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.2.0

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3